services:
  user:
    image: grvbrk/async0:user-latest
    ports:
      - "3000:3000"
    env_file:
      - apps/user/.env.dev
    networks:
      - app-network
      - judge0-network
    depends_on:
      - judge0-server

  admin:
    image: grvbrk/async0:admin-latest
    ports:
      - "3001:3001"
    env_file:
      - apps/user/.env.dev
    networks:
      - app-network
      - judge0-network
    depends_on:
      - judge0-server

  pyserver:
    image: grvbrk/async0:python-latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env.py
    networks:
      - app-network

  judge0-server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - judge0-network

  worker:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - judge0-network

  db:
    image: postgres:13
    env_file:
      - ./judge0.conf
    volumes:
      - judge0-db-data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - judge0-network

  redis:
    image: redis:6.2
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file:
      - ./judge0.conf
    restart: unless-stopped
    networks:
      - judge0-network

volumes:
  judge0-db-data:

networks:
  app-network:
    driver: bridge
  judge0-network:
    driver: bridge
