services:
  traefik:
    image: traefik:v3.4.0
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=gourav@async0.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  user:
    image: grvbrk/async0:user-${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.user.loadbalancer.server.port=3000"
      - "traefik.http.routers.user.rule=Host(`async0.com`)"
      - "traefik.http.routers.user.entrypoints=websecure"
      - "traefik.http.routers.user.tls.certresolver=myresolver"
    DOPPLER_TOKEN: async0_dev_doppler_token

  admin:
    image: grvbrk/async0:admin-${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.admin.loadbalancer.server.port=3001"
      - "traefik.http.routers.admin.rule=Host(`admin.async0.com`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=myresolver"
    DOPPLER_TOKEN: async0_dev_doppler_token

  server:
    image: grvbrk/async0:server-${GIT_COMMIT_HASH:-latest}
    DOPPLER_TOKEN: async0_dev_doppler_token

  redis:
    image: redis:latest
    DOPPLER_TOKEN: async0_dev_doppler_token

  ws:
    image: grvbrk/async0:ws-${GIT_COMMIT_HASH:-latest}
    DOPPLER_TOKEN: async0_dev_doppler_token

  judge0-server:
    image: judge0/judge0:latest
    ports:
      - "2358:2358"
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true

  judge0-worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true

  judge0-db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/

  judge0-redis:
    image: redis:7.2.4
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf

volumes:
  data:
  letsencrypt:
