services:
  traefik:
    image: traefik:v3.4.0
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=gourav@async0.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  user:
    image: grvbrk/async0:user-${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.user.loadbalancer.server.port=3000"
      - "traefik.http.routers.user.rule=Host(`async0.com`)"
      - "traefik.http.routers.user.entrypoints=websecure"
      - "traefik.http.routers.user.tls.certresolver=myresolver"
    configs:
      - source: user-config
        target: ./user.env
        mode: 0444

  admin:
    image: grvbrk/async0:admin-${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.admin.loadbalancer.server.port=3001"
      - "traefik.http.routers.admin.rule=Host(`admin.async0.com`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=myresolver"
    configs:
      - source: admin-config
        target: ./admin.env
        mode: 0444

  pyserver:
    image: grvbrk/async0:python-${GIT_COMMIT_HASH:-latest}
    configs:
      - source: pyserver-config
        target: ./pyserver.env
        mode: 0444

  judge0-server:
    image: judge0/judge0:latest
    ports:
      - "2358:2358"
    configs:
      - source: judge0-config
        target: /judge0.conf
        mode: 0444
    deploy:
      restart_policy:
        condition: any

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    configs:
      - source: judge0-config
        target: /judge0.conf
        mode: 0444
    deploy:
      restart_policy:
        condition: any

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    deploy:
      restart_policy:
        condition: any

  redis:
    image: redis:7.2.4
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    deploy:
      restart_policy:
        condition: any

configs:
  user-config:
    external: true
  admin-config:
    external: true
  pyserver-config:
    external: true
  judge0-config:
    external: true

volumes:
  data:
  letsencrypt:
