import { ProblemTableData } from "./types";

export const problemsData: ProblemTableData[] = [
  {
    id: "prob-1",
    name: "Two Sum",
    topics: ["Array", "HashMap"],
    lists: ["Beginner Problems", "Top Interview Questions"],
    difficulty: "Easy",
    totalUsersSolved: 5421,
    totalBookmarks: 832,
    hasSolved: false,
  },
  {
    id: "prob-2",
    name: "Longest Substring Without Repeating Characters",
    topics: ["String", "Sliding Window"],
    lists: ["Top Interview Questions"],
    difficulty: "Medium",
    totalUsersSolved: 3921,
    totalBookmarks: 659,
    hasSolved: false,
  },
  {
    id: "prob-3",
    name: "Median of Two Sorted Arrays",
    topics: ["Array", "Binary Search"],
    lists: ["Hardcore Challenges"],
    difficulty: "Hard",
    totalUsersSolved: 1582,
    totalBookmarks: 1045,
    hasSolved: false,
  },
  {
    id: "prob-4",
    name: "Valid Parentheses",
    topics: ["Stack"],
    lists: ["Beginner Problems"],
    difficulty: "Easy",
    totalUsersSolved: 7624,
    totalBookmarks: 712,
    hasSolved: false,
  },
  {
    id: "prob-1",
    name: "Two Sum",
    topics: ["Array", "HashMap"],
    lists: ["Beginner Problems", "Top Interview Questions"],
    difficulty: "Easy",
    totalUsersSolved: 5421,
    totalBookmarks: 832,
    hasSolved: false,
  },
  {
    id: "prob-2",
    name: "Longest Substring Without Repeating Characters",
    topics: ["String", "Sliding Window"],
    lists: ["Top Interview Questions"],
    difficulty: "Medium",
    totalUsersSolved: 3921,
    totalBookmarks: 659,
    hasSolved: false,
  },
  {
    id: "prob-3",
    name: "Median of Two Sorted Arrays",
    topics: ["Array", "Binary Search"],
    lists: ["Hardcore Challenges"],
    difficulty: "Hard",
    totalUsersSolved: 1582,
    totalBookmarks: 1045,
    hasSolved: false,
  },
  {
    id: "prob-4",
    name: "Valid Parentheses",
    topics: ["Stack"],
    lists: ["Beginner Problems"],
    difficulty: "Easy",
    totalUsersSolved: 7624,
    totalBookmarks: 712,
    hasSolved: false,
  },
  {
    id: "prob-1",
    name: "Two Sum",
    topics: ["Array", "HashMap"],
    lists: ["Beginner Problems", "Top Interview Questions"],
    difficulty: "Easy",
    totalUsersSolved: 5421,
    totalBookmarks: 832,
    hasSolved: false,
  },
  {
    id: "prob-2",
    name: "Longest Substring Without Repeating Characters",
    topics: ["String", "Sliding Window"],
    lists: ["Top Interview Questions"],
    difficulty: "Medium",
    totalUsersSolved: 3921,
    totalBookmarks: 659,
    hasSolved: false,
  },
  {
    id: "prob-3",
    name: "Median of Two Sorted Arrays",
    topics: ["Array", "Binary Search"],
    lists: ["Hardcore Challenges"],
    difficulty: "Hard",
    totalUsersSolved: 1582,
    totalBookmarks: 1045,
    hasSolved: false,
  },
  {
    id: "prob-4",
    name: "Valid Parentheses",
    topics: ["Stack"],
    lists: ["Beginner Problems"],
    difficulty: "Easy",
    totalUsersSolved: 7624,
    totalBookmarks: 712,
    hasSolved: false,
  },
];
