name: async0-user-admin CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Detect changed apps
    runs-on: ubuntu-latest
    outputs:
      user_changed: ${{ steps.user_diff.outputs.changed }}
      admin_changed: ${{ steps.admin_diff.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if user app changed
        id: user_diff
        run: |
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -qE '^apps/user/|^packages/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if admin app changed
        id: admin_diff
        run: |
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -qE '^apps/admin/|^packages/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build-user-and-push-image:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/user/Dockerfile.user
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/async0:user-latest
            ${{ secrets.DOCKER_USERNAME }}/async0:user-${{ github.sha }}
          provenance: true
          sbom: true

  build-admin-and-push-image:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ./apps/admin
          file: ./apps/admin/Dockerfile.admin
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/async0:admin-latest
            ${{ secrets.DOCKER_USERNAME }}/async0:admin-${{ github.sha }}
          provenance: true
          sbom: true
